name:
    Output Information
on:
    issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "github${{ toJSON(github.event) }}" #Data provided vy GitHub to this job and step
